### ISSUE TITLE
[Bug] resetPasswordPro.php is not resetting passwords

### ISSUE THREAD

**Issue by KrishnaAlagiri** [KrishnaAlagiri/Bhumi-Creatives#12]
**resetPasswordPro.php** is not actually changing passwords. No error message is received.

**Comment by KrishnaAlagiri** [comment]
Also, bootstrap CSS is working as expected. Checked with both ``3.3.7`` and ``4.0.0``. Although ``3.3.7`` seems to be performing better.

**Comment by gsnvsuraj** [comment]
Issue has been fixed.
